repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md] # allow markdown linebreak at EOL
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.6.9"
    hooks:
      - id: ruff
        name: "Ruff linting"
        args:
          - --fix
          - --exit-non-zero-on-fix
      - id: ruff-format
        name: "Ruff formatting"
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: ["--skip", "B101"] # don't check `assert`, as all tests would then raise errors
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
