name: Lint & format codebase

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - release/**
      - pre-release/**

jobs:
  run_hooks:
    name: Enforce pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enforce pre-commits hooks
        uses: pre-commit/action@v3.0.1
